name: feature_initialization
description: Initialization feature — welcome screen with register and login entry points

version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_bloc: ^9.1.1
  injectable: ^2.6.0
  get_it: ^9.0.5
  flora:
    path: ../../design_system/flora
  commons_navigation:
    path: ../../commons/navigation

flutter:
  generate: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  injectable_generator: ^2.12.1
  mocktail: ^1.0.4
