import 'package:flutter/material.dart';
import '../../tokens/flora_colors.dart';

abstract final class FloraColorScheme {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary:            FloraColors.primary,
    onPrimary:          FloraColors.onPrimary,
    primaryContainer:   FloraColors.primaryContainer,
    onPrimaryContainer: FloraColors.onPrimaryContainer,
    secondary:            FloraColors.secondary,
    onSecondary:          FloraColors.onSecondary,
    secondaryContainer:   FloraColors.secondaryContainer,
    onSecondaryContainer: FloraColors.onSecondaryContainer,
    tertiary:            FloraColors.tertiary,
    onTertiary:          FloraColors.onTertiary,
    tertiaryContainer:   FloraColors.tertiaryContainer,
    onTertiaryContainer: FloraColors.onTertiaryContainer,
    error:            FloraColors.error,
    onError:          FloraColors.onError,
    errorContainer:   FloraColors.errorContainer,
    onErrorContainer: FloraColors.onErrorContainer,
    surface:              FloraColors.surface,
    onSurface:            FloraColors.onSurface,
    onSurfaceVariant:     FloraColors.onSurfaceVariant,
    outline:              FloraColors.outline,
    outlineVariant:       FloraColors.outlineVariant,
    inverseSurface:       FloraColors.inverseSurface,
    onInverseSurface:     FloraColors.inverseOnSurface,
    inversePrimary:       FloraColors.inversePrimary,
    scrim:                FloraColors.scrim,
    surfaceContainerLowest:  FloraColors.surfaceContainerLowest,
    surfaceContainerLow:     FloraColors.surfaceContainerLow,
    surfaceContainer:        FloraColors.surfaceContainer,
    surfaceContainerHigh:    FloraColors.surfaceContainerHigh,
    surfaceContainerHighest: FloraColors.surfaceContainerHighest,
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary:            FloraColors.primaryDark,
    onPrimary:          FloraColors.onPrimaryDark,
    primaryContainer:   FloraColors.primaryContainerDark,
    onPrimaryContainer: FloraColors.onPrimaryContainerDark,
    secondary:            FloraColors.secondaryDark,
    onSecondary:          FloraColors.onSecondaryDark,
    secondaryContainer:   FloraColors.secondaryContainerDark,
    onSecondaryContainer: FloraColors.onSecondaryContainerDark,
    tertiary:            FloraColors.tertiaryDark,
    onTertiary:          FloraColors.onTertiaryDark,
    tertiaryContainer:   FloraColors.tertiaryContainerDark,
    onTertiaryContainer: FloraColors.onTertiaryContainerDark,
    error:            FloraColors.errorDark,
    onError:          FloraColors.onErrorDark,
    errorContainer:   FloraColors.errorContainerDark,
    onErrorContainer: FloraColors.onErrorContainerDark,
    surface:              FloraColors.surfaceDark,
    onSurface:            FloraColors.onSurfaceDark,
    onSurfaceVariant:     FloraColors.onSurfaceVariantDark,
    outline:              FloraColors.outlineDark,
    outlineVariant:       FloraColors.outlineVariantDark,
    inverseSurface:       FloraColors.inverseSurfaceDark,
    onInverseSurface:     FloraColors.inverseOnSurfaceDark,
    inversePrimary:       FloraColors.inversePrimaryDark,
    scrim:                FloraColors.scrim,
    surfaceContainerLowest:  FloraColors.surfaceContainerLowestDark,
    surfaceContainerLow:     FloraColors.surfaceContainerLowDark,
    surfaceContainer:        FloraColors.surfaceContainerDark,
    surfaceContainerHigh:    FloraColors.surfaceContainerHighDark,
    surfaceContainerHighest: FloraColors.surfaceContainerHighestDark,
  );
}
